import _ from 'lodash';
import Bluebird from 'bluebird';
import bcrypt from 'bcrypt';
import * as yup from 'yup';

import { UserInputError } from 'services/errors';
import User from 'models/user';
import { sendEmail } from 'services/email';

export default async function sendResetEmailPassword({ input }) {
  const { email } = await validateInputs();

  return Bluebird
    .resolve(findLocaUserByEmail())
    .then(generateResetCodes)
    .tap(sendPasswordResetEmail);

  //

  function findLocaUserByEmail() {
    return User
      .query()
      .findOne({
        email
      })
      .then((user) => {
        if (_.isEmpty(user)) {
          throw new UserInputError('Email not found', { code: 'email_not_found' });
        } else {
          return user
            .$relatedQuery('verifications')
            .then((verifications) => {
              if (_.isEmpty(verifications)) {
                throw new UserInputError('Email not found', { code: 'email_not_found' });
              } else {
                const localProvider = _.find(verifications, { providerName: 'local' });

                const socialProviders = _.chain(verifications)
                  .filter(({ providerName }) => providerName !== 'local')
                  .map('providerName')
                  .value();

                if (_.isEmpty(socialProviders)) {
                  return localProvider;
                } else {
                  throw new UserInputError('Social Login', { code: 'social_login', providers: socialProviders });
                }
              }
            });
        }
      });
  }

  async function generateResetCodes(verification) {
    const resetHash = await resetTheHash();
    const resetCode = resetTheCode();

    return verification
      .$query()
      .patch({
        resetHash,
        resetCode
      })
      .then(() => ({
        token: resetHash,
        code: resetCode
      }));

    //

    async function resetTheHash() {
      const salt = await bcrypt.genSalt();

      return bcrypt.hash(verification.hash, salt);
    }

    function resetTheCode() {
      return `${_.random(1000, 9999)}-${_.random(1000, 9999)}`;
    }
  }

  function sendPasswordResetEmail({ code }) {
    const body = _.template(passwordResetEmail)({ code });

    return sendEmail({
      to: email,
      subject: 'SOAPEE.COM - Password Reset',
      body
    });
  }

  function validateInputs() {
    return schema.validate(input);
  }
}

const schema = yup.object().shape({
  email: yup.string().email().required()
});

const passwordResetEmail = `
A password reset was requested for your http://soapee.com account.

Enter the following code Reset Code to start your password reset process: 

code: <%= code %>

It is safe to ignore this email if this password reset request was NOT generated by you.
`;
